# Generated by Django 2.2.6 on 2020-01-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200101_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectitem',
            name='project',
        ),
    ]
