# Generated by Django 2.2.6 on 2020-01-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectitem_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectitem',
            options={'ordering': ['-content_time']},
        ),
        migrations.AddField(
            model_name='projectitem',
            name='content_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
