# Generated by Django 2.2.6 on 2019-12-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugitem',
            name='content_type',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
