# Generated by Django 2.2.6 on 2019-12-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0002_bugitem_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugitem',
            name='content_description',
            field=models.TextField(default='Please add a description.'),
        ),
        migrations.AddField(
            model_name='bugitem',
            name='content_title',
            field=models.TextField(default='Please add a Title.'),
        ),
    ]
