# Generated by Django 2.2.6 on 2019-12-24 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0003_auto_20191224_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugitem',
            name='content_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bugitem',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
