# Generated by Django 2.2.6 on 2019-12-26 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugtracker', '0004_auto_20191224_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugitem',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bugitem',
            name='content_description',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='bugitem',
            name='content_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bugitem',
            name='content_title',
            field=models.TextField(default='None'),
        ),
    ]
