# Generated by Django 2.2.6 on 2019-12-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0005_auto_20191226_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugitem',
            options={'ordering': ['-content_time']},
        ),
    ]
