# Generated by Django 2.2.6 on 2020-01-01 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_projectitem_project'),
        ('bugtracker', '0006_auto_20191228_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugitem',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectItem'),
            preserve_default=False,
        ),
    ]
